wandb_version: 1

learning_rate:
  desc: null
  value: 0.02
architecture:
  desc: null
  value: QNN
dataset:
  desc: null
  value: 'NO'
epochs:
  desc: null
  value: 100
_wandb:
  desc: null
  value:
    python_version: 3.9.12
    cli_version: 0.15.5
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1689248856.499875
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 16
      - 23
      4: 3.9.12
      5: 0.15.5
      8:
      - 1
      - 5
